CREATE TABLE IF NOT EXISTS worker (
    ID INTEGER PRIMARY KEY AUTO_INCREMENT ,
    NAME VARCHAR(1000) NOT NULL CHECK (length(NAME) >= ? AND length(NAME) <= ?),
    BIRTHDAY DATE CHECK (YEAR(BIRTHDAY) > ?),
    LEVEL VARCHAR(7) NOT NULL CHECK (LEVEL IN (?, ?, ?, ?)),
    SALARY INTEGER NOT NULL CHECK (SALARY >= ? AND SALARY <= ?)
);